### ISSUE TITLE
Console History

### ISSUE THREAD

**Issue by yilinxia** [VMarkos/prudens-viz-temp#2]
Is there a reason we keep the history of the console output?

I do think we can remain the history maybe for V2.0 since the provenance information is important for users to go back and forth. However for now, I propose to only show the context for the current Policy input to simplify the process and reduce cognitive load.

**Comment by yilinxia** [comment]
I have revised the code and it will only show the current console output, which we can keep discussing.

**Comment by VMarkos** [comment]
No, I think we can keep showing just the current output for now. I also fixed the part where the new graph is being updated - so far it was just appended, not replacing the previous one.
