### ISSUE TITLE
Repo and Branch Org

### ISSUE THREAD

**Issue by yilinxia** [VMarkos/prudens-viz-temp#3]
Maybe we can get rid of the redudant files if we decides to switch to D3.js ? I created a new branch called prudenvis and delete the unnecessary part for better understanding the code.

Is there a plan for us to hold the repo such as will it be in your personal repo OR maybe later it will become part of a organization repo?

**Comment by VMarkos** [comment]
Well, we discuss this into more detail into our next meeting. I think that, if we decide to stick to d3.js, we should indeed get rid of anything else but for the `./pure-version` directory, as you did. We will keep both until then, just to make sure nothing useful is lost.
